version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: scripts/docker_install.sh
      timeout: 300
      runas: root
    - location: scripts/dns-services.sh
      timeout: 300
      runas: root
    - location: scripts/haproxy-external.sh
      timeout: 300
      runas: root
